### ISSUE TITLE
[Typo mistake in a quest]

### ISSUE THREAD

**Issue by Felix201b** [TheComputerizer/Dimension-Hopper-The-Fall#8]
**Version**
[1.5.5]

**Questline**
[Bosses & challeges]

**Quest**
[Ender Dragon, 10]

**Describe the issue**
[Its is guardian not gaurdian]

**Comment by Felix201b** [comment]
You have also made a typo mistake in the name of the questline it is challenges not challeges.
,

**Comment by TheComputerizer** [comment]
Fixed in 1.5.6
