### ISSUE TITLE
Game still refuses to start after launching

### ISSUE THREAD

**Issue by m4n02** [TheComputerizer/Dimension-Hopper-The-Fall#9]
**Version**
1.1.5 Release

**Log**
https://mclo.gs/efqSO8o

**Describe the issue**
Upon launching the client, the instance refuses to load, given some seconds. To further add, the ram usage freezes on the java instance, as seen on task manager.

**To Reproduce**

- Step 1: Open the modpack via curseforge.
- Step 2: Click launch.
- Step 3: Watch as the java runtime freezes. Nothing happens from there.

**Additional context**
Just like the last crash report. The problem still persists through the new version.

**Comment by TheComputerizer** [comment]
This can be fixed by setting `B:optimizeFMLRemapper=false` in the `remapper` section of `config/normalasm.cfg`. The fix will also be included in 1.5.6 this weekend.

**Comment by TheComputerizer** [comment]
Fixed int 1.5.6
